# Generated by Django 3.1 on 2021-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('cough', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('fever', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('throat', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('breathe', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('ha', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('senior', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('sit', models.CharField(choices=[('Contact', 'Contact'), ('Abroad', 'Abroad'), ('Other', 'Other')], max_length=15)),
            ],
        ),
    ]
