# Generated by Django 3.1 on 2021-09-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='predictor',
        ),
    ]
